services:
  mlops-api: 
    image: andresmartinezfuentes8/mlops-api-sinerror
    container_name: mlops-api
    ports:
      - "6000:5000"
    restart: always
  mlops-web:
    image: andresmartinezfuentes8/mlops-web-sinerror
    container_name: mlops-web
    ports:
      - "8080:8501" 
    environment:
      - API_URL=http://mlops-api:5000/predict 
    depends_on:
      - mlops-api
    restart: always
